baseurl: "/"
url: "http://ellekasai.github.io"
title: "Co-Lab"

# Add default author configuration
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Anonymous"  # Default author for posts

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title

# Excerpt settings
excerpt_separator: <!--more-->
show_excerpts: true